services:

  api:
    build: .
    container_name: employee_api

    ports:
      - "8000:8000"

    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/people_flow_db

    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16

    container_name: employee_db

    restart: always

    environment:
      POSTGRES_DB: people_flow_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d people_flow_db"]
      interval: 5s
      timeout: 5s
      retries: 10

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: