services:

  api:
    build: .
    container_name: employee_api

    ports:
      - "8000:8000"

    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/people_flow_db

    depends_on:
      - db

  db:
    image: postgres:16

    container_name: employee_db

    restart: always

    environment:
      POSTGRES_DB: employees_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: